version: '2'
services:
  chemicalsearch-mysql:
    image: mysql:8.0.33-oracle
    # volumes:
    #     - ~/volumes/jhipster/chemicalsearch/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=demoms
      - MYSQL_PASSWORD=msDB!2023
      - MYSQL_ROOT_PASSWORD=ms!2023
      - MYSQL_DATABASE=chemicalsearch
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
